;规则集定义
ruleset=🎯 全球直连,https://raw.githubusercontent.com/iwakuralain451/rule/refs/heads/main/direct.ini
ruleset=Gemini,https://raw.githubusercontent.com/iwakuralain451/rule/refs/heads/main/Gemini.ini
ruleset=Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Spotify/Spotify.list
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=🎯 GoogleFCM,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GoogleFCM/GoogleFCM.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Advertising/Advertising.list
ruleset=🛡️ 隐私防护,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎞️ Microsoft,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Microsoft/Microsoft.list
ruleset=🍀 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=💧 Copilot,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Copilot/Copilot.list
ruleset=🐬 OneDrive,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.list
ruleset=🎵 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,[]GEOIP,LAN,no-resolve
ruleset=🎯 全球直连,[]GEOSITE,CN
ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
ruleset=🐟 漏网之鱼,[]FINAL
;ruleset=REJECT,[]NETWORK,udp

;策略组定义
custom_proxy_group=🚀 节点选择`select`[]🐸 手动切换`[]♻️ 自动选择`[]家宽`[]🇭🇰 香港节点-自动`[]🇯🇵 日本节点-自动`[]🇺🇲 美国节点-自动`[]🇨🇳 台湾节点-自动`[]🇸🇬 狮城节点-自动`[]🇰🇷 韩国节点-自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🛩️ 高速节点`[]🕊️便宜节点`[]🕊️便宜节点-自动`[]🛩️ 中转节点-自动`[]DIRECT
custom_proxy_group=🐸 手动切换`select`.*
custom_proxy_group=♻️ 自动选择`url-test`^(?!.*南极)(?!.*\[)(?!.*下载专用).*$`https://www.gstatic.com/generate_204/`60,5,100
custom_proxy_group=非中国节点`select`^(?=.*(^(?!.*(香港|HK|Hong Kong|测试|俄罗斯|缅甸|越南|南极|下方|下载专用)).*))(?!.*\[).*$
custom_proxy_group=🇭🇰 香港节点`select`^(?=.*(香港|HK|Hong Kong))(?!.*\[).*$
custom_proxy_group=🇯🇵 日本节点`select`^(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan))(?!.*\[)(?!.*下载专用).*$
custom_proxy_group=🇺🇲 美国节点`select`^(?=.*(美|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|United States|(?<![a-zA-Z])US(?![a-zA-Z])|(?<![a-zA-Z])USA(?![a-zA-Z])|(?<![a-zA-Z])USD(?![a-zA-Z])))(?!.*\[).*$
custom_proxy_group=🇨🇳 台湾节点`select`^(?=.*(台|新北|彰化|TW|Taiwan))(?!.*\[).*$
custom_proxy_group=🇸🇬 狮城节点`select`^(?=.*(新加坡|坡|狮城|SG|Singapore))(?!.*\[).*$
custom_proxy_group=🇰🇷 韩国节点`select`^(?=.*(KR|Korea|KOR|首尔|韩|韓))(?!.*\[).*$
custom_proxy_group=家宽`select`.*(家宽|家庭宽带).*
custom_proxy_group=🛩️ 高速节点`select`(?=.*(中转))
custom_proxy_group=🕊️便宜节点`select`(?=.*(x0.1|x1|x0.3|0.5|0.5倍|0.5x|x0.5|x0.3))
custom_proxy_group=Spotify`select`[]🐸 手动切换`[]非中国节点`[]非中国节点-自动`[]🇭🇰 香港节点-自动`[]🇯🇵 日本节点-自动`[]🇺🇲 美国节点-自动`[]🇨🇳 台湾节点-自动`[]🇸🇬 狮城节点-自动`[]🇰🇷 韩国节点-自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🛩️ 高速节点`[]🕊️便宜节点`[]DIRECT
custom_proxy_group=Gemini`select`[]🐸 手动切换`[]非中国节点`[]非中国节点-自动`[]🇭🇰 香港节点-自动`[]🇯🇵 日本节点-自动`[]🇺🇲 美国节点-自动`[]🇨🇳 台湾节点-自动`[]🇸🇬 狮城节点-自动`[]🇰🇷 韩国节点-自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🛩️ 高速节点`[]🕊️便宜节点`[]DIRECT
custom_proxy_group=🎞️ Microsoft`select`[]🚀 节点选择`[]♻️ 自动选择`[]🐸 手动切换`[]非中国节点`[]非中国节点-自动`[]🇭🇰 香港节点-自动`[]🇯🇵 日本节点-自动`[]🇺🇲 美国节点-自动`[]🇨🇳 台湾节点-自动`[]🇸🇬 狮城节点-自动`[]🇰🇷 韩国节点-自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🛩️ 高速节点`[]🕊️便宜节点`[]DIRECT
custom_proxy_group=🍀 Google`select`[]🚀 节点选择`[]♻️ 自动选择`[]🐸 手动切换`[]非中国节点`[]非中国节点-自动`[]🇭🇰 香港节点-自动`[]🇯🇵 日本节点-自动`[]🇺🇲 美国节点-自动`[]🇨🇳 台湾节点-自动`[]🇸🇬 狮城节点-自动`[]🇰🇷 韩国节点-自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🛩️ 高速节点`[]🕊️便宜节点`[]DIRECT
custom_proxy_group=🎯 GoogleFCM`select`[]🚀 节点选择`[]♻️ 自动选择`[]🐸 手动切换`[]非中国节点`[]非中国节点-自动`[]🇭🇰 香港节点-自动`[]🇯🇵 日本节点-自动`[]🇺🇲 美国节点-自动`[]🇨🇳 台湾节点-自动`[]🇸🇬 狮城节点-自动`[]🇰🇷 韩国节点-自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🛩️ 高速节点`[]🕊️便宜节点`[]DIRECT
custom_proxy_group=💧 Copilot`select`[]🚀 节点选择`[]♻️ 自动选择`[]🐸 手动切换`[]非中国节点`[]非中国节点-自动`[]🇭🇰 香港节点-自动`[]🇯🇵 日本节点-自动`[]🇺🇲 美国节点-自动`[]🇨🇳 台湾节点-自动`[]🇸🇬 狮城节点-自动`[]🇰🇷 韩国节点-自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🛩️ 高速节点`[]🕊️便宜节点`[]DIRECT
custom_proxy_group=🐬 OneDrive`select`[]🚀 节点选择`[]♻️ 自动选择`[]🐸 手动切换`[]非中国节点`[]非中国节点-自动`[]🇭🇰 香港节点-自动`[]🇯🇵 日本节点-自动`[]🇺🇲 美国节点-自动`[]🇨🇳 台湾节点-自动`[]🇸🇬 狮城节点-自动`[]🇰🇷 韩国节点-自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🛩️ 高速节点`[]🕊️便宜节点`[]DIRECT
custom_proxy_group=📲 Telegram`select`[]🚀 节点选择`[]♻️ 自动选择`[]🐸 手动切换`[]非中国节点`[]非中国节点-自动`[]🇭🇰 香港节点-自动`[]🇯🇵 日本节点-自动`[]🇺🇲 美国节点-自动`[]🇨🇳 台湾节点-自动`[]🇸🇬 狮城节点-自动`[]🇰🇷 韩国节点-自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🛩️ 高速节点`[]🕊️便宜节点`[]DIRECT
custom_proxy_group=📹 YouTube`select`[]🚀 节点选择`[]♻️ 自动选择`[]🐸 手动切换`[]非中国节点`[]非中国节点-自动`[]🇭🇰 香港节点-自动`[]🇯🇵 日本节点-自动`[]🇺🇲 美国节点-自动`[]🇨🇳 台湾节点-自动`[]🇸🇬 狮城节点-自动`[]🇰🇷 韩国节点-自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🛩️ 高速节点`[]🕊️便宜节点`[]DIRECT
custom_proxy_group=🎵 TikTok`select`[]🚀 节点选择`[]♻️ 自动选择`[]🐸 手动切换`[]非中国节点`[]非中国节点-自动`[]🇭🇰 香港节点-自动`[]🇯🇵 日本节点-自动`[]🇺🇲 美国节点-自动`[]🇨🇳 台湾节点-自动`[]🇸🇬 狮城节点-自动`[]🇰🇷 韩国节点-自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🛩️ 高速节点`[]🕊️便宜节点`[]DIRECT
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]♻️ 自动选择`[]🐸 手动切换`[]非中国节点`[]非中国节点-自动`[]🇭🇰 香港节点-自动`[]🇯🇵 日本节点-自动`[]🇺🇲 美国节点-自动`[]🇨🇳 台湾节点-自动`[]🇸🇬 狮城节点-自动`[]🇰🇷 韩国节点-自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🛩️ 高速节点`[]🕊️便宜节点`[]DIRECT
custom_proxy_group=非中国节点-自动`url-test`^(?=.*(^(?!.*(香港|HK|Hong Kong|测试|俄罗斯|缅甸|越南|南极|下载专用)).*))(?!.*\[).*$`https://www.gstatic.com/generate_204/`60,5,100
custom_proxy_group=🇭🇰 香港节点-自动`url-test`^(?=.*(香港|HK|Hong Kong))(?!.*\[).*$`https://www.gstatic.com/generate_204/`60,5,100
custom_proxy_group=🇯🇵 日本节点-自动`url-test`^(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan))(?!.*\[)(?!.*下载专用).*$`https://www.gstatic.com/generate_204/`60,5,100
custom_proxy_group=🇺🇲 美国节点-自动`url-test`^(?=.*(美|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|United States|(?<![a-zA-Z])US(?![a-zA-Z])|(?<![a-zA-Z])USA(?![a-zA-Z])|(?<![a-zA-Z])USD(?![a-zA-Z])))(?!.*\[).*$`https://www.gstatic.com/generate_204/`60,5,100
custom_proxy_group=🇨🇳 台湾节点-自动`url-test`^(?=.*(台|新北|彰化|TW|Taiwan))(?!.*\[).*$`https://www.gstatic.com/generate_204/`60,5,100
custom_proxy_group=🇸🇬 狮城节点-自动`url-test`^(?=.*(新加坡|坡|狮城|SG|Singapore))(?!.*\[).*$`https://www.gstatic.com/generate_204/`60,5,100
custom_proxy_group=🇰🇷 韩国节点-自动`url-test`^(?=.*(KR|Korea|KOR|首尔|韩|韓))(?!.*\[).*$`https://www.gstatic.com/generate_204/`60,5,100
custom_proxy_group=🛩️ 中转节点-自动`url-test`(?=.*(中转))`https://www.gstatic.com/generate_204/`60,5,100
custom_proxy_group=🕊️便宜节点-自动`url-test`(?=.*(x0.1|x1|x0.3|0.5|0.5倍|0.5x|x0.5|x0.3))`https://www.gstatic.com/generate_204/`60,5,100
custom_proxy_group=🧱 9.9机场`select`^.*\[.*$
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点-自动`[]🇯🇵 日本节点-自动`[]🇺🇲 美国节点-自动`[]🇨🇳 台湾节点-自动`[]🇸🇬 狮城节点-自动`[]🇰🇷 韩国节点-自动`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇰🇷 韩国节点`[]🛩️ 高速节点`[]🕊️便宜节点
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]🐸 手动切换
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🛡️ 隐私防护`select`[]REJECT`[]DIRECT

;启用自定义规则集
enable_rule_generator=true
overwrite_original_rules=true
